on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: [completed]

name: Publish on Netlify

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@master
    
    - name: Webhook
      uses: calvertjadon/Personal-Website@main
      with:
        url: ${{ secrets.WEBHOOK_URL }}
